name: CI/CD Pipeline for Flask App

on:
  push:
    branches:
      - main
      - staging
  pull_request:
    branches:
      - main
      - staging
  release:
    types: [published]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          echo "Running tests..."
          pytest || echo "No tests found, skipping."

  deploy-staging:
    runs-on: ubuntu-latest
    needs: build-test
    if: github.ref == 'refs/heads/staging'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Simulated deploy to staging
        run: |
          echo "Deploying Flask app to STAGING environment..."
          echo "Deployment complete (simulated)"

  deploy-production:
    runs-on: ubuntu-latest
    needs: build-test
    if: github.event_name == 'release'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Simulated deploy to production
        run: |
          echo "Deploying Flask app to PRODUCTION environment..."
          echo "Production deployment complete (simulated)"